# Generated by Django 2.2.9 on 2020-03-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfiparticipationstatus',
            old_name='rfi_status',
            new_name='status',
        ),
    ]
