# Generated by Django 2.2.9 on 2020-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200310_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontacts',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
