# Generated by Django 2.2.9 on 2020-03-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20200324_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfis',
            name='rfi_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Opened', 'Opened'), ('Issued', 'Issued')], default='Created', max_length=50),
        ),
    ]
