# Generated by Django 2.2.9 on 2020-03-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200312_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.Vendors'),
        ),
    ]
