# Generated by Django 2.2.9 on 2020-02-25 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20200221_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analystnotes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='analystsflaggedelements',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assignedpcanalysts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assignedvendorsanalysts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calendarmodules',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calendarvendors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chartsparticipation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='elementsattachments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='moduleelements',
            name='id',
        ),
        migrations.RemoveField(
            model_name='modulepersonas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pricescores',
            name='id',
        ),
        migrations.RemoveField(
            model_name='referencemodules',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rfiparticipation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rfiparticipationstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selfdescriptions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selfscores',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='smscores',
            name='id',
        ),
        migrations.RemoveField(
            model_name='surveyanswers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendormodulenames',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weightscategories',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weightselements',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weightssurveyquestions',
            name='id',
        ),
        migrations.AlterField(
            model_name='analystnotes',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='analystsflaggedelements',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='assignedpcanalysts',
            name='analyst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedvendorsanalysts',
            name='analyst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarmodules',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Calendar'),
        ),
        migrations.AlterField(
            model_name='calendarvendors',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Calendar'),
        ),
        migrations.AlterField(
            model_name='chartsparticipation',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='elementsattachments',
            name='e',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Elements'),
        ),
        migrations.AlterField(
            model_name='moduleelements',
            name='m',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Modules'),
        ),
        migrations.AlterField(
            model_name='modulepersonas',
            name='m',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Modules'),
        ),
        migrations.AlterField(
            model_name='pricescores',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='referencemodules',
            name='reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.References'),
        ),
        migrations.AlterField(
            model_name='rfiparticipation',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='selfdescriptions',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='selfscores',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='m',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Modules'),
        ),
        migrations.AlterField(
            model_name='smscores',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='surveyanswers',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='vendormodulenames',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.Vendors'),
        ),
        migrations.AlterField(
            model_name='weightscategories',
            name='m',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Modules'),
        ),
        migrations.AlterField(
            model_name='weightselements',
            name='m',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Modules'),
        ),
        migrations.AlterField(
            model_name='weightssurveyquestions',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='vendors.Personas'),
        ),
    ]
