# Generated by Django 2.2.9 on 2020-03-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20200324_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
