# Generated by Django 2.2.9 on 2020-03-16 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20200316_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_name',
            field=models.CharField(choices=[('Sourcing', 'Sourcing'), ('SA', 'SA'), ('SXM', 'SXM'), ('CLM', 'CLM'), ('ePRO', 'ePRO'), ('I2P', 'I2P'), ('P2P', 'P2P'), ('SPT', 'SPT'), ('S2P', 'S2P'), ('AP', 'AP'), ('TS', 'TS'), ('SOW', 'SOW'), ('ICW', 'ICW')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
