# Generated by Django 2.2.9 on 2020-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20200316_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcontacts',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
