# Generated by Django 2.2.9 on 2020-03-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20200326_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipation',
            name='m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_modules', to='vendors.Modules'),
        ),
        migrations.AlterField(
            model_name='rfiparticipation',
            name='rfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_rfi', to='vendors.Rfis'),
        ),
        migrations.AlterField(
            model_name='rfiparticipation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_vendor', to='vendors.Vendors'),
        ),
    ]
