# Generated by Django 2.2.9 on 2020-03-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_auto_20200326_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='rfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_rfis_status', to='vendors.Rfis'),
        ),
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_vendor_status', to='vendors.Vendors'),
        ),
    ]
