# Generated by Django 2.2.9 on 2020-03-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20200326_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfiparticipationstatus',
            name='m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_modules_status', to='vendors.Modules'),
        ),
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.ParentCategories'),
        ),
    ]
