# Generated by Django 2.2.9 on 2020-03-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20200320_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodulenames',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendor_modules', to='vendors.Vendors'),
        ),
    ]
