# Generated by Django 2.2.9 on 2020-03-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_auto_20200328_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='m',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_modules_status', to='vendors.Modules'),
            preserve_default=False,
        ),
    ]
