# Generated by Django 2.2.9 on 2020-03-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_auto_20200331_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='office',
            field=models.CharField(max_length=145),
        ),
    ]
