# Generated by Django 2.2.9 on 2020-03-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_auto_20200331_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipation',
            name='rfi',
            field=models.ForeignKey(default='20R1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_rfi', to='vendors.Rfis'),
        ),
    ]
