# Generated by Django 2.2.9 on 2020-04-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_historicalvendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendors',
            name='vendorid',
            field=models.IntegerField(blank=True, db_index=True, default=15),
            preserve_default=False,
        ),
    ]
