# Generated by Django 2.2.9 on 2020-04-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_auto_20200403_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontacts',
            name='email',
            field=models.CharField(blank=True, error_messages={'unique': 'Email already exists'}, max_length=80, null=True, unique=True),
        ),
    ]
