# Generated by Django 2.2.9 on 2020-04-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_auto_20200404_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipation',
            name='rfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rfi', to='vendors.Rfis'),
        ),
    ]
