# Generated by Django 2.2.9 on 2020-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_auto_20200406_1247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rfiparticipation',
            unique_together={('vendor', 'm', 'rfi')},
        ),
    ]
