# Generated by Django 2.2.9 on 2020-04-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_auto_20200406_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_name',
            field=models.CharField(choices=[('Sourcing', 'Sourcing'), ('Supplier Management', 'Supplier Management'), ('Spend Analytics', 'Spend Analytics'), ('Contract Management', 'Contract Management'), ('e-Procurement', 'e-Procurement'), ('Invoice-to-Pay', 'Invoice-to-Pay'), ('Strategic Procurement', 'Strategic Procurement'), ('Technologies', 'Technologies'), ('Procure-to-Pay', 'Procure-to-Pay'), ('Source-to-Pay', 'Source-to-Pay')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parentcategories',
            name='parent_category_name',
            field=models.CharField(choices=[('Common S2P', 'Common S2P'), ('Common Sourcing - SXM', 'Common Sourcing - SXM'), ('Services', 'Services'), ('Sourcing', 'Sourcing'), ('SXM', 'SXM'), ('Spend Analytics', 'Spend Analytics'), ('CLM', 'CLM'), ('eProcurement', 'eProcurement'), ('I2P', 'I2P')], default='Common S2P', max_length=45, unique=True),
        ),
    ]
