# Generated by Django 2.2.9 on 2020-04-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0026_auto_20200410_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategories',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
