# Generated by Django 2.2.9 on 2020-04-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0028_auto_20200410_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategories',
            name='parent_category_name',
            field=models.CharField(choices=[('Common S2P', 'Common S2P'), ('Common Sourcing - SXM', 'Common Sourcing - SXM'), ('Services', 'Services'), ('Sourcing', 'Sourcing'), ('SXM', 'SXM'), ('Spend Analytics', 'Spend Analytics'), ('CLM', 'CLM'), ('eProcurement', 'eProcurement'), ('I2P', 'I2P')], max_length=45, unique=True),
        ),
    ]
