# Generated by Django 2.2.9 on 2020-04-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0029_auto_20200410_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='rfi',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_rfis_status', to='vendors.Rfis'),
        ),
    ]
