# Generated by Django 2.2.9 on 2020-04-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0030_auto_20200412_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='rfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_rfis_status', to='vendors.Rfis'),
        ),
    ]
