# Generated by Django 2.2.9 on 2020-04-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0032_auto_20200413_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='office',
            field=models.CharField(blank=True, max_length=145, null=True),
        ),
    ]
