# Generated by Django 2.2.9 on 2020-04-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0034_auto_20200415_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfscores',
            name='e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='self_score', to='vendors.Elements'),
        ),
    ]
