# Generated by Django 2.2.9 on 2020-04-23 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0035_auto_20200420_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_name',
            field=models.CharField(choices=[('Strategic Sourcing', 'Strategic Sourcing'), ('Supplier Management', 'Supplier Management'), ('Spend Analytics', 'Spend Analytics'), ('Contract Management', 'Contract Management'), ('e-Procurement', 'e-Procurement'), ('Invoice-to-Pay', 'Invoice-to-Pay'), ('Strategic Procurement Technologies', 'Strategic Procurement Technologies'), ('Procure-to-Pay', 'Procure-to-Pay'), ('Source-to-Pay', 'Source-to-Pay'), ('AP Automation', 'AP Automation')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyGeneralInfoQuestion',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=512)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.Rfis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_info__questions',
            },
        ),
        migrations.CreateModel(
            name='CompanyGeneralInfoAnswers',
            fields=[
                ('answerid', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=4096, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.CompanyGeneralInfoQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.Vendors')),
            ],
            options={
                'db_table': 'company_info_answers',
            },
        ),
    ]
