# Generated by Django 2.2.9 on 2020-04-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0037_auto_20200424_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_to_question', to='vendors.CompanyGeneralInfoQuestion'),
        ),
    ]
