# Generated by Django 2.2.9 on 2020-04-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0038_auto_20200424_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_to_question', to='vendors.CompanyGeneralInfoQuestion'),
        ),
    ]
