# Generated by Django 2.2.9 on 2020-04-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0039_auto_20200424_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.Vendors'),
        ),
    ]
