# Generated by Django 2.2.9 on 2020-04-24 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0040_auto_20200424_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_to_question', to='vendors.CompanyGeneralInfoQuestion'),
        ),
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.Vendors'),
        ),
    ]
