# Generated by Django 2.2.9 on 2020-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0042_historicalcompanygeneralinfoanswers_historicalcompanygeneralinfoquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfiparticipationstatus',
            name='m',
        ),
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
