# Generated by Django 2.2.9 on 2020-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0046_auto_20200507_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedvendorsanalysts',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
