# Generated by Django 2.2.9 on 2020-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0047_assignedvendorsanalysts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='last_analyst_response',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='last_vendor_response',
            field=models.IntegerField(default=0),
        ),
    ]
