# Generated by Django 2.2.9 on 2020-05-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0049_auto_20200518_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcompanygeneralinfoquestion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcompanygeneralinfoquestion',
            name='rfi',
        ),
        migrations.RemoveField(
            model_name='historicalcompanygeneralinfoquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='companygeneralinfoanswers',
            name='scoring',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.DeleteModel(
            name='HistoricalCompanyGeneralInfoAnswers',
        ),
        migrations.DeleteModel(
            name='HistoricalCompanyGeneralInfoQuestion',
        ),
    ]
