# Generated by Django 2.2.9 on 2020-05-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0050_auto_20200519_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygeneralinfoanswers',
            name='scoring',
            field=models.IntegerField(default=0),
        ),
    ]
