# Generated by Django 2.2.9 on 2020-05-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0051_auto_20200519_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsattachments',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='vendors.Attachments'),
        ),
    ]
