# Generated by Django 2.2.9 on 2020-05-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0052_auto_20200520_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsattachments',
            name='attachement_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='elementsattachments',
            unique_together={('e', 'id', 'rfi', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='elementsattachments',
            name='attachment',
        ),
    ]
