# Generated by Django 2.2.9 on 2020-05-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0053_auto_20200520_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementsattachments',
            old_name='attachement_info',
            new_name='attachment_info',
        ),
    ]
