# Generated by Django 2.2.9 on 2020-05-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0054_auto_20200520_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsattachments',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.Vendors'),
        ),
        migrations.AlterUniqueTogether(
            name='elementsattachments',
            unique_together={('e', 'vendor', 'rfi', 'timestamp')},
        ),
    ]
