# Generated by Django 2.2.9 on 2020-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0055_auto_20200520_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='initialize',
            field=models.BooleanField(default=False),
        ),
    ]
