# Generated by Django 2.2.9 on 2020-05-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0056_elements_initialize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesParentCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Modules')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.ParentCategories')),
            ],
        ),
    ]
