# Generated by Django 2.2.9 on 2020-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0058_initialize_models_parent_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='parent_categories',
            field=models.ManyToManyField(related_name='_modules_parent_categories_+', through='vendors.ModulesParentCategories', to='vendors.ParentCategories'),
        ),
        migrations.AddField(
            model_name='parentcategories',
            name='modules',
            field=models.ManyToManyField(through='vendors.ModulesParentCategories', to='vendors.Modules'),
        ),
    ]
