# Generated by Django 2.2.9 on 2020-05-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0059_auto_20200527_0902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modulesparentcategories',
            unique_together={('module', 'parent_category')},
        ),
    ]
