# Generated by Django 2.2.9 on 2020-05-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0060_auto_20200527_1001'),
        ('vendors', '0057_auto_20200527_1421'),
    ]

    operations = [
    ]
