# Generated by Django 2.2.9 on 2020-05-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0062_auto_20200529_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfiparticipationstatus',
            name='status',
            field=models.CharField(choices=[('Invited', 'Invited'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Created', 'Created'), ('Outstanding', 'Outstanding'), ('Received', 'Received'), ('Scored', 'Scored'), ('Closed', 'Closed')], default='Invited', max_length=50),
        ),
    ]
