# Generated by Django 2.2.9 on 2020-06-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0064_auto_20200601_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcat', to='vendors.ParentCategories'),
        ),
        migrations.AlterField(
            model_name='elements',
            name='s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub', to='vendors.Subcategories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cat', to='vendors.Categories'),
        ),
    ]
