# Generated by Django 2.2.9 on 2020-06-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0065_auto_20200608_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedvendorsanalysts',
            name='pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.ParentCategories'),
        ),
        migrations.AlterField(
            model_name='assignedvendorsanalysts',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
